import json
import os
from datetime import datetime

class ReportingEngine:
    """
    Generates high-density Mission Reports in Markdown format.
    Summarizes findings, assets, and tactical attack paths.
    """
    
    def __init__(self):
        pass

    def generate_markdown(self, results):
        """Generates a professional Markdown report from scan results."""
        scan_id = results.get('scan_id', 'Unknown')
        target = results.get('target', 'Unknown')
        status = results.get('status', 'Unknown')
        start_time = results.get('metrics', {}).get('start_time', 'Unknown')
        duration = results.get('metrics', {}).get('duration_seconds', 0)
        
        findings = results.get('findings', [])
        assets = results.get('assets', [])
        
        # Sort findings by severity
        severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
        sorted_findings = sorted(findings, key=lambda x: severity_order.get(x.get('severity', 'info').lower(), 5))

        report = f"# 🏹 RedOps3 Mission Report: {target}\n"
        report += f"**Scan ID**: `{scan_id}` | **Status**: `{status.upper()}` | **Date**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n\n"
        
        report += "## 📊 Executive Summary\n"
        report += f"The security assessment of **{target}** has been completed. "
        
        crit_count = len([f for f in findings if f.get('severity') == 'critical'])
        high_count = len([f for f in findings if f.get('severity') == 'high'])
        
        if crit_count > 0 or high_count > 0:
            report += f"The scan identified **{crit_count} Critical** and **{high_count} High** severity vulnerabilities. "
            report += "Immediate remediation is recommended for these high-impact findings.\n\n"
        else:
            report += "No critical or high severity vulnerabilities were identified during this assessment.\n\n"

        report += "### 📈 Risk Distribution\n"
        report += "| Severity | Count |\n"
        report += "| :--- | :--- |\n"
        for sev in ['critical', 'high', 'medium', 'low', 'info']:
            count = len([f for f in findings if f.get('severity') == sev])
            report += f"| {sev.upper()} | {count} |\n"
        report += "\n"

        report += "## 🛠️ Technical Findings\n"
        if not sorted_findings:
            report += "No significant findings were recorded.\n"
        else:
            for f in sorted_findings:
                sev_icon = "🔴" if f.get('severity') == 'critical' else "🟠" if f.get('severity') == 'high' else "🟡" if f.get('severity') == 'medium' else "🔵"
                report += f"### {sev_icon} {f.get('title', 'Untitled Finding')}\n"
                report += f"**Severity**: `{f.get('severity', 'INFO').upper()}` | **Tool**: `{f.get('tool_source', 'N/A')}`\n\n"
                report += f"#### Description\n{f.get('description', 'No description provided.')}\n\n"
                
                if f.get('endpoint'):
                    report += f"**Target/Endpoint**: `{f.get('endpoint')}`\n\n"
                
                if f.get('repro_command'):
                    report += f"#### Reproduction\n```bash\n{f.get('repro_command')}\n```\n\n"
                
                if f.get('metadata') and f['metadata'].get('exfil_scoring'):
                    score = f['metadata']['exfil_scoring']
                    report += f"#### 📂 Data Leakage (Exfiltration Score: {score.get('risk_score')})\n"
                    for pii_type, data in score.get('pii_matches', {}).items():
                        report += f"- **{pii_type}**: Found {data['count']} matches. Samples: `{', '.join(data['samples'])}`\n"
                    report += "\n"

                report += "---\n\n"

        report += "## 🌐 Attack Surface Details\n"
        report += f"**Total Assets Discovered**: {len(assets)}\n\n"
        report += "| Asset Type | Identifer | Source |\n"
        report += "| :--- | :--- | :--- |\n"
        for asset in assets[:50]: # Limit to top 50 in report
            report += f"| {asset.get('category', 'N/A')} | {asset.get('artifact', 'N/A')} | {asset.get('sensor', 'N/A')} |\n"
        
        if len(assets) > 50:
            report += f"\n*...and {len(assets) - 50} more assets were identified.*"

        report += "\n\n## 🔗 Lateral Movement Paths\n"
        tactical = results.get('phases', {}).get('tactical', {}).get('lateral_paths', [])
        if tactical:
            for path in tactical:
                report += f"- **{path['title']}**: {path['description']}\n"
                report += f"  - Source: `{path.get('source')}` ➔ Destination: `{path.get('destination')}`\n"
        else:
            report += "No multi-stage lateral movement paths were identified.\n"

        report += "\n\n---\n*Generated by RedOps3 Mission Intelligence Engine.*"
        
        return report
