from core.extensions import db
from app import create_app
from core.models import Scan, KnowledgeNode, KnowledgeEdge
from core.results_store import load_results
from scan_engine.helpers.attack_graph import AttackGraphBuilder
import json

app = create_app()
with app.app_context():
    # Helper to persist
    def persist_graph_cb(scan_id, nodes, edges):
        try:
            KnowledgeEdge.query.filter_by(scan_id=scan_id).delete()
            KnowledgeNode.query.filter_by(scan_id=scan_id).delete()
            
            for node in nodes:
                # Ensure label
                label = node.get('label')
                if not label:
                    label = f"{node.get('type')}:{node.get('id')}"
                
                kn = KnowledgeNode(
                    scan_id=scan_id,
                    node_id=node.get('id'),
                    type=node.get('type'),
                    label=label,
                    metadata_json=node.get('data')
                )
                db.session.add(kn)
            
            for edge in edges:
                ke = KnowledgeEdge(
                    scan_id=scan_id,
                    source_node=edge.get('from'),
                    target_node=edge.get('to'),
                    relationship=edge.get('type'),
                    metadata_json=edge.get('data')
                )
                db.session.add(ke)
            
            db.session.commit()
            print(f"Persisted graph for Scan {scan_id}: {len(nodes)} nodes, {len(edges)} edges")
        except Exception as e:
            print(f"Failed to persist graph for Scan {scan_id}: {e}")
            db.session.rollback()

    scans = Scan.query.all()
    for s in scans:
        results = load_results(s.id)
        if results:
            # Inject findings from DB if possible to be more up-to-date
            # though builder uses results file mainly.
            builder = AttackGraphBuilder()
            graph_data = builder.build(results)
            nodes = graph_data.get('nodes', [])
            edges = graph_data.get('edges', [])
            if nodes:
                persist_graph_cb(s.id, nodes, edges)
            else:
                print(f"Scan {s.id}: No nodes generated by builder.")
        else:
            print(f"Scan {s.id}: No results file found.")
